### ISSUE TITLE
[Roadmap] Refactor Visuomotor Control Evaluation

### ISSUE THREAD

**Issue by siddk** [siddk/voltron-evaluation#1]
Currently, both the Franka Kitchen & Adroit Visuomotor Control Tasks are implemented on top of the [R3M evaluation code](https://github.com/facebookresearch/r3m/tree/eval/evaluation). While a fairly straightforward addition to that codebase, it would be nice to:

- [ ] Programmatically download demonstration data + setup simulation dependencies (via `pip`)
- [ ] Refactor existing training/online evaluation to fit with the general V-Evaluation Harness API
- [ ] Add simple `argparse` layer for specifying splits/evaluation subsets (given 7 environments, 3 demonstration splits, etc.)

Targeting refactor by 3/4/23; happy to prioritize if folks want this sooner!
