### ISSUE TITLE
[Roadmap] Acquire WHiRL Videos for Intent Scoring Example

### ISSUE THREAD

**Issue by siddk** [siddk/voltron-evaluation#2]
Check with Shikhar + co. around sharing the video examples from the [WHiRL website](https://human2robot.github.io/) - possibly get more examples. Then:

- [ ] Upload videos to GDrive add simple `gdown` script to acquire.
- [ ] Port intent scoring into an example, under the V-Evaluation Harness (may require a refactor?)
- [ ] (Maybe) Add real-time visualization component – or minimally, export to GIF
